# Generated by Django 5.2.4 on 2025-07-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('name', models.CharField(help_text='Полное наименование компании', max_length=200, verbose_name='Название компании')),
                ('short_name', models.CharField(blank=True, help_text='Краткое название для удобства отображения', max_length=100, verbose_name='Краткое название')),
                ('company_type', models.CharField(choices=[('manufacturer', 'Производитель'), ('distributor', 'Дистрибьютор'), ('integrator', 'Интегратор'), ('end_user', 'Конечный пользователь'), ('other', 'Другое')], default='end_user', max_length=20, verbose_name='Тип компании')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('potential', 'Потенциальный'), ('inactive', 'Неактивный'), ('blacklist', 'Черный список')], default='potential', max_length=20, verbose_name='Статус')),
                ('inn', models.CharField(blank=True, help_text='Идентификационный номер налогоплательщика', max_length=12, verbose_name='ИНН')),
                ('ogrn', models.CharField(blank=True, help_text='Основной государственный регистрационный номер', max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(blank=True, verbose_name='Фактический адрес')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('industry', models.CharField(blank=True, help_text='Основная отрасль деятельности', max_length=200, verbose_name='Отрасль')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='Приблизительный годовой оборот в рублях', max_digits=15, null=True, verbose_name='Годовой оборот')),
                ('employees_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество сотрудников')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о компании', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('sales_manager', models.ForeignKey(blank=True, help_text='Sales менеджер, ответственный за данную компанию', limit_choices_to={'role': 'sales'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_companies', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный менеджер')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['name'],
            },
        ),
    ]
