# Generated by Django 5.2.4 on 2025-07-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='restored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='transaction_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='actual_address',
            field=models.TextField(blank=True, null=True, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('not_defined', 'Не определен'), ('manufacturer', 'Производитель'), ('distributor', 'Дистрибьютор'), ('integrator', 'Интегратор'), ('end_user', 'Конечный пользователь'), ('other', 'Другое')], default='end_user', max_length=20, verbose_name='Тип компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, help_text='Основная отрасль деятельности', max_length=200, null=True, verbose_name='Отрасль'),
        ),
        migrations.AlterField(
            model_name='company',
            name='legal_address',
            field=models.TextField(blank=True, null=True, verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='company',
            name='notes',
            field=models.TextField(blank=True, help_text='Дополнительная информация о компании', null=True, verbose_name='Заметки'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, help_text='Основной государственный регистрационный номер', max_length=15, null=True, verbose_name='ОГРН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, help_text='Краткое название для удобства отображения', max_length=100, null=True, verbose_name='Краткое название'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('not_defined', 'Не определен'), ('active', 'Активный'), ('potential', 'Потенциальный'), ('inactive', 'Неактивный'), ('blacklist', 'Черный список')], default='potential', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Веб-сайт'),
        ),
    ]
