# Generated by Django 5.2.4 on 2025-07-31 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_company_deleted_at_company_restored_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('not_defined', 'Не определен'), ('manufacturer', 'Производитель'), ('distributor', 'Дистрибьютор'), ('integrator', 'Интегратор'), ('end_user', 'Конечный пользователь'), ('other', 'Другое')], default='not_defined', max_length=20, verbose_name='Тип компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
    ]
