# Generated by Django 5.2.4 on 2025-07-31 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_company_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(help_text='Полное наименование компании', max_length=255, verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, help_text='Краткое название для удобства отображения', max_length=512, null=True, verbose_name='Краткое название'),
        ),
    ]
