# Generated by Django 5.2.4 on 2025-07-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_company_name_alter_company_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='inn',
            field=models.CharField(blank=True, help_text='Идентификационный номер налогоплательщика', max_length=50, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='company',
            name='ogrn',
            field=models.CharField(blank=True, help_text='Основной государственный регистрационный номер', max_length=50, null=True, verbose_name='ОГРН'),
        ),
    ]
