# Generated by Django 5.2.4 on 2025-07-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='ext_id',
            field=models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ext_id',
            field=models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='productgroup',
            name='ext_id',
            field=models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='productsubgroup',
            name='ext_id',
            field=models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
    ]
