# Generated by Django 5.2.4 on 2025-07-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_brand_ext_id_alter_product_ext_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tech_params',
            field=models.JSONField(blank=True, default=dict, help_text='Технические характеристики товара в формате JSON', verbose_name='Технические параметры'),
        ),
    ]
