# Generated by Django 5.2.4 on 2025-07-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_product_deleted_at_product_restored_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='complex_name',
            field=models.CharField(default=1, help_text='Комплексное наименование товара', max_length=512, verbose_name='Комплексное наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Описание товара', verbose_name='Описание'),
        ),
    ]
