# Generated by Django 5.2.4 on 2025-07-23 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='Внешний идентификатор из внешней базы', max_length=100, null=True, unique=True, verbose_name='Внешний ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(help_text='Рабочий email адрес', max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, help_text='Рабочий телефон', max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(blank=True, help_text='Должность в компании', max_length=200, verbose_name='Должность')),
                ('department', models.CharField(blank=True, help_text='Отдел или подразделение', max_length=200, verbose_name='Отдел')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('suspended', 'Приостановлен')], default='active', max_length=20, verbose_name='Статус')),
                ('is_primary_contact', models.BooleanField(default=False, help_text='Является ли основным контактным лицом в компании', verbose_name='Основной контакт')),
                ('notes', models.TextField(blank=True, help_text='Дополнительная информация о контакте', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('company', models.ForeignKey(help_text='Компания, в которой работает человек', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='customer.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Контактное лицо',
                'verbose_name_plural': 'Контактные лица',
                'ordering': ['company', 'last_name', 'first_name'],
                'unique_together': {('company', 'email')},
            },
        ),
    ]
