# Generated by Django 5.2.4 on 2025-08-03 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiemail',
            options={'verbose_name': 'Письмо AI', 'verbose_name_plural': 'Письма AI'},
        ),
        migrations.CreateModel(
            name='AiEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_id', models.UUIDField(blank=True, null=True)),
                ('file', models.FileField(upload_to='ai_email_attachments/', verbose_name='Файл')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя файла')),
                ('ai_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='email_marketing.aiemail', verbose_name='Письмо')),
            ],
            options={
                'verbose_name': 'Файл письма AI',
                'verbose_name_plural': 'Файлы письма AI',
            },
        ),
    ]
